server:
  port: 8093

spring:
  application:
    name: uaa
    
user:
  service: user-dev
  
eureka:
  client:
    service-url:
      defaultZone: http://192.168.111.129:8091/eureka
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    
service:
  shop: shop-dev
  user: user-dev
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enable: true
      show-details: ALWAYS