server:
  port: 8094

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://192.168.111.129:3306/userCenter?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: zhongliang
    password: Qq,!123456
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enable: true
      show-details: ALWAYS

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.111.129:8091/eureka
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}