server:
  port: 9092

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
eureka:
  client:
    service-url:
      defaultZone: http://www.aitkeke.com:8091/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    ip-address: 116.21.13.16