server:
  port: 8096

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  redis:
    database: 0
    host: 192.168.111.129        
    port: 6379             
    password: 123456
    pool:
      max-active: 200     
      max-idle: 10       
      max-wait: -1      
      min-idle: 0        
    timeout: 1000
eureka:
  client:
    service-url:
      defaultZone: http://192.168.111.129:8091/eureka
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    
reactor:
  netty:
    http:
      server:
        accessLogEnabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enable: true
      show-details: ALWAYS
auth:
  whiteList:
    - /oauth/check_token
    - /oauth/token
    - /dict/queryAll
    - /userAuth/regist
    - /userInfo/add
  url: 
    http://localhost:8093