server:
  port: 8095

spring:
  application:
    name: base-dev
  datasource:
    url: jdbc:mysql://192.168.111.129:3306/base?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: zhongliang
    password: Qq,!123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.111.129        
    port: 6379             
    password: 123456
    pool:
      max-active: 200     
      max-idle: 10       
      max-wait: -1      
      min-idle: 0        
    timeout: 1000         
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enable: true
      show-details: ALWAYS

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.111.129:8091/eureka
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}